### ISSUE TITLE
Dialects error

### ISSUE THREAD

**Issue by Vilen5** [Super-Thomate/HousePointsDiscordBot#17]
I get this error whenever I type "nodde index.js" even thought I created a mysql db and entred all info correctly
![image-18](https://github.com/Super-Thomate/HousePointsDiscordBot/assets/140520966/c87fc118-445e-40f3-a436-a8d856d37f91)

**Comment by Super-Thomate** [comment]
I'll check when i'm home

**Comment by Vilen5** [comment]
It was my issue for not creating a .env file in a proper way
